---

dispatcher_config: apache/author                           # location of the files and templates to generate the dispatcher configuration.
group_apache_gid: 1100

##  Templating dispatcher.any
dispatcher_name: internet-server                           # name of the dispatcher
dispatcher_cache_docroot: /data/httpd/cache                # document root for files cached in the dispatcher
render_hostname: 0.0.0.0                                   # hostname or ip for AEM instance to retrieve content
render_port: 4502

## apache httpd conf
apache_version: apache2.4                                  # apache version to install
dispatcher_version: 4.1.12                                 # apache dispatcher module version to configure
apache_user: apache                                        # DEPRECATED: run apache as this user
apache_group: apache                                       # DEPRECATED: dispatcher version to configure
apache_log_level: info                                     # set the logging level

##  Docker repository usage
docker_images_pull: no
docker_images_push: no                                     # using docker in isolation by default. set to yes to push to private registry.
docker_images_force: yes                                   # rebuild all docker images by default.

docker_repository: 10.32.64.11:5000                        # Docker registry to push and pull images from

docker_image_tag_aem_apache: 1                           # Build tag for the apache httpd docker image
docker_image_tag_aem_dispatcher: 1                         # Build tag for the dispatcher docker image
docker_image_tag_aem_dispatcher_author: 1.4                         # Build tag for the dispatcher author docker image
docker_image_tag_aem_dispatcher_publisher: 1.3                         # Build tag for the dispatcher publisher docker image

docker_container_name: dispatcher                          # Dispatcher docker container name
docker_dns_servers: []
docker_image: aem-dispatcher
docker_dispatcher_published_port:
  - "80:8080/tcp"
  - "443:8443/tcp"
docker_published_ports: "{{ docker_dispatcher_published_port }}"
docker_keep_volumes: true                                  # Retain volumes associated with a removed container.
docker_volume_driver: local
docker_volumes:                                            # Sets the docker volumes to the host.
  - "/var/dispatcher/cache:/data/httpd/cache:z"
  - "/var/dispatcher/logs:/data/httpd/logs:z"

docker:
  api_version: 1.22
  timezone: "Asia/Hong_Kong"

volume_info:
  volume_group: rhel
  logical_volume: "{{ docker_container_name }}"
  size: 10g
  mount_point: "/var/{{ docker_container_name }}"
  mapping: "rhel-{{ docker_container_name }}"
  fstype: xfs
  is_encrypted: false