---

docker:
  api_version: 1.22
  timezone: "Asia/Hong_Kong"

##  Docker repository usage
docker_images_pull: no
docker_images_push: no                                      # using docker in isolation by default. set to yes to push to private registry.

docker_repository: 10.72.76.85:5000                             # Docker registry to push and pull images from
docker_registry_use: no                                     # yes to use private registry
docker_images_force: yes                                    # rebuild all docker images by default.

docker_registry_username: admin                             # parameter for 'docker login --username'
docker_registry_password: admin123                          # parameter for 'docker login --password'
docker_registry_email: devops@wkcda.hk

docker_container_name: gitlabce
docker_image: gitlab
docker_image_tag: 1
docker_published_ports:
    - "8922:22/tcp"
    - "8980:80/tcp"
    - "8943:433/tcp"
docker_volumes:
    - "/var/{{ docker_container_name }}/etc/gitlab:/etc/gitlab:rw"
    - "/var/{{ docker_container_name }}/var/opt/gitlab:/var/opt/gitlab:rw"
    - "/var/{{ docker_container_name }}/var/log/gitlab:/var/log/gitlab:rw"

volume_info:
  volume_group: rhel
  logical_volume: "{{ docker_container_name }}"
  size: 10g
  mount_point: "/var/{{ docker_container_name }}"
  mapping: "rhel-{{ docker_container_name }}"
  fstype: xfs
  is_encrypted: false