---
# file: group_vars/jenkins

iptable:
  rules:
    - chain: INPUT
      protocol: tcp
      match: tcp
      port: 8080
      jump_target: ACCEPT
    - chain: INPUT
      protocol: tcp
      match: tcp
      port: 50000
      jump_target: ACCEPT