---

# file: group_vars/processing

docker_image_tag: 1.3                                         # Latest aem base image to build and run
docker_image_tag_aem: 1.4                                         # Latest aem image to build and run

aem_offloading_port: 4522
aem_host: "{{ ansible_host }}"
aem_port: "{{ aem_offloading_port }}"
aem_jvm_opts: "-server -Xms4096m -Xmx8192m -XX:MaxDirectMemorySize=1024m -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true"
service_processing_username: "admin"
service_processing_password: "admin"
aem_username: "{{ service_processing_username }}"
aem_password: "{{ service_processing_password }}"
aem_topology_host_ip: "{{ ansible_host }}"
aem_topology_host_port: "{{ aem_offloading_port }}"
aem_topology_connector_urls: "author01.service.dc1.consul:4502"

consul_service_name: processing

docker_network_mode: bridge
docker_network_name:
  - name: bridge
  - name: "{{ consul_network_name }}"

docker_volume_driver: local
docker_volumes:
  - "/var/lib/rancher/convoy/devicemapper/mounts/{{ docker_container_name }}:/aem/crx-quickstart"
  - "/var/lib/rancher/convoy/devicemapper/mounts/{{ docker_container_name }}-datastore:/aem/datastore"
  - "/var/lib/rancher/convoy/devicemapper/mounts/{{ docker_container_name }}-tmp:/tmp"

volume_info: []

aem_runmode: "author,processing,{{ consul_environment }},nosamplecontent"

# role/aem
docker_aem_published_port: "{{ aem_offloading_port }}:{{ aem_port }}/tcp"

include: aem-packages-files.yml

stop_timeout: 3600