---

- name: configure network interfaces
  template:
    src: "network-scripts.{{ item.template | default('default') }}.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.conn_name }}"
  become: yes
  tags:
    - configure-network-interfaces
