---

docker_images_push: yes

docker_registry_username: admin
docker_registry_password: admin123
docker_registry_email: devops@wkcda.hk

docker_dns_servers:
  - "{{ ansible_host }}"

docker_repository: 10.32.64.11:5000
maven_repository: 10.32.64.11:8081

# docker-container
docker_keep_volumes: false                                  # Remove all data when containers are removed.

consul_dns_primary: 8.8.8.8                                 # IP address of the consul DNS. Docker network will be configured to this.
consul_dns_secondary: 8.8.4.4

# consul-server
docker_consul_net_driver: bridge                            # Sets the network driver for the Docker container. Options: [bridge|overlay|host]
consul_environment: develop
consul_host: "{{ ansible_host }}"                           # Registrator registers services with this consul host
consul_dns:                                                 # IP address of the consul DNS. Docker network will be configured to this.
  - "{{ consul_dns_primary }}"
  - "{{ consul_dns_secondary }}"
consul_network_name: consul-net

# docker-host
docker_daemon_template: default                             # Configures /etc/sysconfig/docker. Options: [default|cluster]

docker_aem_published_port: "{{ aem_port }}:{{ aem_port }}/tcp"

snmp_src: "10.72.36.40/32"

esb_repository_url: http://10.32.64.11:8081/repository/maven-snapshots/

nfs_share: "DAM_NFS_Dev"