---
- name: test if docker service is running
  command: systemctl status docker
  ignore_errors: yes
  changed_when: false
  register: docker_status
  no_log: True

- name: Create temp directory
  shell: "mktemp -d"
  register: mktemp
  tags:
    - docker-images-build

- name: copy docker files
  synchronize:
    src: docker/
    dest: "{{ mktemp.stdout }}"
  tags:
    - docker-images-build

- name: login to private docker repository
  docker_login:
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    registry: "{{ docker_repository }}"
    email: "{{ docker_registry_email }}"
  when: docker_images_push == "yes"
  become: yes
  tags:
    - docker-images-build

- name: build jenkins base image
  docker_image:
    path: "{{ mktemp.stdout }}/jenkins-base/{{ docker_image_tag_jenkins_base }}"
    name: devops/jenkins-base
    tag: "{{ docker_image_tag_jenkins_base }}"
    state: present
    force: "{{ docker_images_force }}"
    push: "{{ docker_images_push }}"
    pull: "{{ docker_images_pull }}"
    repository: "{{ docker_repository }}/devops/jenkins-base"
  become: yes
  become_method: sudo
  tags:
    - docker-images-build
    - docker-images-build-jenkins-base

- name: build jenkins image
  docker_image:
    path: "{{ mktemp.stdout }}/jenkins/{{ docker_image_tag_jenkins }}"
    name: jenkins
    tag: "{{ docker_image_tag_jenkins }}"
    state: present
    force: "{{ docker_images_force }}"
    push: "{{ docker_images_push }}"
    pull: "{{ docker_images_pull }}"
    repository: "{{ docker_repository }}/devops/jenkins"
  become: yes
  become_method: sudo
  register: jenkins_image_exist
  until: jenkins_image_exist|success
  retries: 5
  delay: 1
  tags:
    - docker-images-build
    - docker-images-build-jenkins

- name: Change jenkins home owner
  file:
    path: "/var/lib/rancher/convoy/devicemapper/mounts/{{ docker_container_name }}"
    owner: "{{ uid }}"
    group: "{{ uid }}"
    state: directory
    recurse: yes
  become: yes
  become_method: sudo
  tags:
    - create-jenkins-lv

- name: starting jenkins container
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_repository }}/{{ docker_image }}:{{ docker_image_tag_jenkins }}"
    state: started
    privileged: true
    published_ports: "{{ docker_published_ports }}"
    networks:
      - name: consul-net
    volumes: "{{ docker_volumes }}"
    labels:
      "CONSUL_SERVICE_IP={{ docker_container_name }}.{{ consul_network_name }}"
    env:
      TZ: "{{ docker.timezone }}"
      SERVICE_TAGS: "{{ consul_environment }}"
      SERVICE_NAME: "{{ consul_service_name }}"
  become: yes
  become_method: sudo
  tags:
    - docker-start-jenkins

- name: removing temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  tags:
    - docker-images-build
    - docker-images-build-jenkins
    - docker-images-build-jenkins-base