---

- name: update sshd config
  template:
    src=sshd_config.j2
    dest=/etc/ssh/sshd_config
  become: yes
  tags:
    - configure-sshd

- name: configure sshd_config permission
  file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  become: yes
  tags:
    - configure-sshd

- name: restart sshd service
  service:
    name: sshd
    state: restarted
  become: yes
  tags:
    - configure-sshd