---

##  Docker repository usage
docker_images_pull: no                                      # enable pulling of FROM image
docker_images_push: no                                      # using docker in isolation by default. set to yes to push to private registry.
docker_images_force: yes                                    # rebuild all docker images by default.

docker_repository: 10.32.64.11:5000                         # Docker registry to push and pull images from

consul_service_name: nexus

docker_registry_username: admin                             # parameter for 'docker login --username'
docker_registry_password: admin123                          # parameter for 'docker login --password'
docker_registry_email: devops@wkcda.hk

docker_container_name: nexus
docker_image: devops/nexus
docker_image_tag: 1
docker_published_ports:
    - "5000:5000/tcp"
    - "8081:8081/tcp"
docker_volumes:
    - "/var/lib/rancher/convoy/devicemapper/mounts/{{ docker_container_name }}:/nexus-data:rw"

docker:
  api_version: 1.22
  timezone: "Asia/Hong_Kong"

uid: 200

volume_info:
  volume_group: rhel
  logical_volume: nexus
  size: 10g
  mount_point: /var/nexus
  mapping: rhel-nexus
  fstype: xfs
  is_encrypted: false