---

  - name: Add VM Authorized Keys to account
    lineinfile:
      dest: "{{ authorized_keys_dest }}"
      line: "{{ lookup('file', item ) }}"
      state: present
      create: yes
    with_lines: ls -1 ../wkcd-vm/keys/current/*.pub
    tags:
      - security-rotate-keys
      - add-allow-servicekeys


  - name: Remove VM Authorized Keys
    lineinfile:
      dest: "{{ authorized_keys_dest }}"
      line: "{{ lookup('file', item ) }}"
      state: absent
      create: yes
    with_lines: ls -1 ../wkcd-vm/keys/old/*.pub
    tags:
      - security-rotate-keys
      - remove-deny-servicekeys
