---

docker_images_force: no
docker_images_push: no
docker_images_pull: yes                                     # Enable pulling FROM images

docker_registry_username: admin
docker_registry_password: admin123
docker_registry_email: devops@wkcda.hk

# Configured on Docker containers
docker_dns_servers:
  - 10.32.64.94
  - 10.32.64.96

docker_repository: 10.32.64.11:5000
maven_repository: 10.32.64.11:8081

consul_dns_primary: 8.8.8.8                                 # IP address of the consul DNS. Docker network will be configured to this.
consul_dns_secondary: 8.8.4.4

# consul-server
docker_consul_net_driver: bridge                            # Sets the network driver for the Docker container. Options: [bridge|overlay|host]
consul_environment: production
consul_host: "{{ ansible_host }}"                           # Registrator registers services with this consul host
consul_dns:                                                 # IP address of the consul DNS. Docker network will be configured to this.
  - "{{ consul_dns_primary }}"
  - "{{ consul_dns_secondary }}"
consul_network_name: consul-net

# docker-host
docker_daemon_template: default                             # Configures /etc/sysconfig/docker. Options: [default|cluster]

docker_aem_published_port: "{{ aem_port }}:{{ aem_port }}/tcp"

docker_keep_volumes: true                                   # Remove all data when containers are removed.

nfs_share: "DAM_NFS_PROD"