---
galaxy_info:
  author: devops@wkcda.hk
  description: Creates and mounts an logical volume
  company: rxps services
  license: Apache
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
      - 7
  categories: system
dependencies: []
  
